### ISSUE TITLE
.env file missing

### ISSUE THREAD

**Issue by ronmegini** [masfranzhuo/flutter_nft_minting#1]
`.env` file ,which is required in assets, is missing in this project

Error log:
```
No file or variants found for asset: .env.
```

Asset reference:
```
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/abi/nft.json
```
